Tests in pytest
DebugCove/DisSafe-Shield-API pull request #9
Opened 2024-11-29 00:51 UTC by Everaldo451

2024-11-29 01:22 UTC, LuisGomes18 requested changes
The pull request needs a few changes, both to those indicated and to the formatting of the code, which is different from the standard used in the repository. Please make the necessary changes so that the merge can be carried out.

2024-11-29 01:22 UTC, LuisGomes18 commented on tests/test_route.py
> +def createTokenRow(db, authTokenValue):
The definition is not essential, and allows the user to create tokens irregularly, which constitutes a security risk for the API.

2024-11-29 01:22 UTC, LuisGomes18 commented on tests/test_route.py
> +def requestData():
The information provided for the report is not limited to these.

2024-11-29 11:25 UTC, Everaldo451 commented on app/modules/main/route.py
> -
I solved this. I did a new commit and added the line.

2024-11-29 11:34 UTC, Everaldo451 commented on tests/test_route.py
> +def requestData():
It isn't a problem, because this data will be modified each new test, to verify each case.

2024-11-30 01:47 UTC, LuisGomes18 requested changes
Changes marked in the comments but it shows that there has been an improvement in the code

2024-11-30 01:47 UTC, LuisGomes18 commented on tests/integration/report_tests/conftest.py
> +        "report_time":"",
Form of generation with date needs to separate date and time

2024-11-30 01:47 UTC, LuisGomes18 commented on tests/integration/report_tests/conftest.py
> +        "server_id":"1",
Server id incorrectly just a number needs an official id

2024-11-30 01:47 UTC, LuisGomes18 commented on tests/integration/report_tests/conftest.py
> +        "proof": "http://imgur.com, http://flickr.com",
Links from eradicate url path required

2024-11-30 01:47 UTC, LuisGomes18 commented on tests/integration/report_tests/conftest.py
> +            query = "INSERT INTO Report (%s) VALUES (%s)"
Wrong way to make a querry leaving SQL inject security

2024-11-30 01:47 UTC, LuisGomes18 commented on tests/integration/report_tests/test_invalid_username.py
> +        response = client.post(f"{url_prefix}/report",
Unnecessary API access url since the api route doesn't change

2024-11-30 01:48 UTC, LuisGomes18 commented
@Everaldo451

2024-12-03 16:48 UTC, LuisGomes18 commented on app/db/db.py
It was not possible to understand the code indicated and the possible recommendations. We ask that comments with recommendations are preferably sent via GitHub or Discord, rather than shared via text.

2024-12-03 17:00 UTC, LuisGomes18 requested changes
O commit atual não atende aos requisitos solicitados. Foram encontradas falhas graves no código, que já foram devidamente comentadas. Além disso, foi observado que todos os testes estão utilizando a definição `def test()`. Solicitamos que os nomes das definições sejam alterados, pois, caso seja necessário juntar o código a outro arquivo, isso pode gerar conflitos. Pedimos também que as modificações indicadas nos comentários do código sejam realizadas para corrigir os problemas reportados.

2024-12-08 20:51 UTC, LuisGomes18 requested changes
The test is feasible to pull, the only thing missing is to change 1 value in the code that is in the comments, otherwise the test will move to the main.

2024-12-08 20:51 UTC, LuisGomes18 commented on tests/integration/report_tests/conftest.py
> +        "bot": "anybot",
It should be a boolean value True or False

2024-12-08 21:43 UTC, LuisGomes18 approved these changes
Test successfully accepted

2024-12-08 21:45 UTC, merged